version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - .:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  web:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./public:/code/public
      - ./docker/nginx/conf.d/local.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    environment:
      - TZ=${TZ}
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
